server:
  port: 8083
  servlet:
    context-path: /integracao

spring:
  application:
    name: integracao
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    open-in-view: false
    generate-ddl: true
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka
    
integracao:
  ipea:
    url:
      series: 'https://www.ipea.gov.br/atlasviolencia/api/v1/series'
      valores-por-regiao: 'https://www.ipea.gov.br/atlasviolencia/api/v1/valores-series-por-regioes/{serie_id}/4/{regioes}'
      