server:
  port: 8083
  servlet:
    context-path: /integracao

spring:
  application:
    name: integracao
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/
#    username: postgres
#    password: postgres
    url: jdbc:postgresql://ec2-54-166-242-77.compute-1.amazonaws.com:5432/d488m40vk4mlb9?user=cfvhtpknlvtkkv
    password: 7ae52abc843d579579dee6d91b6307700e80b59fa2afdbe5c2a4c5b338a80a50
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    open-in-view: false
    generate-ddl: false
    
eureka:
  instance:
    hostname: http://tcc-discovery.herokuapp.com
  client:
    service-url:
#      defaultZone: http://localhost:8761/registry/eureka
      defaultZone: http://tcc-discovery.herokuapp.com/registry/eureka/
    
integracao:
  ipea:
    url:
      series: 'https://www.ipea.gov.br/atlasviolencia/api/v1/series'
      valores-por-regiao: 'https://www.ipea.gov.br/atlasviolencia/api/v1/valores-series-por-regioes/{serie_id}/4/{regioes}'
      